name: Hello World Workflow

on:
  push:
    branches:
      - main  # or 'master', depending on your default branch

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World!"
